package secondlife.network.vituz.ranks.redis;

public enum RankSubscriberAction {
	
	ADD_RANK, DELETE_RANK, SET_RANK_PREFIX, SET_RANK_SUFFIX, ADD_GRANT,
	
	DELETE_GRANT, IMPORT_RANKS, ADD_RANK_PERMISSION, DELETE_RANK_PERMISSION, ADD_PLAYER_PERMISSION,
	
	DELETE_PLAYER_PERMISSION, ADD_INHERITANCE, DELETE_INHERITANCE;
}
